nav:
    - NLP: NLP.md
    - Book-Natural-Language-Processing-with-Python: Book-Natural-Language-Processing-with-Python
    - Task-of-NLP: Task-of-NLP.md
    - Part-of-speech-tagging: Part-of-speech-tagging
    - Shallow-parsing: shallow-parsing